namespace Penguin.Net.Whois.Objects
{
    /// <summary>
    /// This class contains raw request-response data for use in debugging
    /// </summary>
    public class ServerResponse
    {
        #region Properties

        /// <summary>
        /// The query string the server was sent
        /// </summary>
        public string Request { get; set; }

        /// <summary>
        /// The raw response generated by the server
        /// </summary>
        public string Response { get; set; }

        /// <summary>
        /// The server that was connected to
        /// </summary>
        public string Server { get; set; }

        #endregion Properties
    }
}